CHAT_ONLY = "Chat-Only"
OPEN = "Open-Ended"
CLOSED = "Closed"

KILL_MESSAGE = "<bot>: See you soon! Bye!"

REDPAJAMA_CHAT_3B_CONSTANT="RedPajama 3B"
REDPAJAMA_CHAT_7B_CONSTANT="RedPajama 7B"
VICUNA_CHAT_7B_CONSTANT="Vicuna 7B"
VICUNA_15_CHAT_7B_CONSTANT="Vicuna LLAMA2 7B"

SANTA_CODER_1B_CONSTANT="SantaCoder 1B"
CODEGEN_25_7B_CONSTANT="CodeGen 2.5 7B"

GPT_3_5 = "gpt-3.5-turbo"
GPT_4 = "gpt-4"